### ISSUE TITLE
Dependency on https://github.com/robotology/boost-mil missing

### ISSUE THREAD

**Issue by Tobias-Fischer** [robotology/iol#11]
Actually, it's not missing, but this error is thrown:
```
/home/icub/robot/iol/src/milClassifier/main.cpp:41:45: fatal error: iCub/boostMIL/ClassifierFactory.h: No such file or directory
 #include <iCub/boostMIL/ClassifierFactory.h>
```

boostMIL is installed.

**Comment by pattacini** [comment]
uhm... I didn't get you last comment; working on it

**Comment by pattacini** [comment]
it just compiles fine...
@Tobias-Fischer, could you please check whether the `boostMIL` header files are installed in `$ICUBcontrib_DIR/include` ?

**Comment by Tobias-Fischer** [comment]
Issue resolved after deleting the `build`. Sorry! Must have been to tired last night.

**Comment by pattacini** [comment]
Never mind, it happens!
