### ISSUE TITLE
lbpExtractor crashes

### ISSUE THREAD

**Issue by pattacini** [robotology/iol#16]
`lbpExtractor` occasionally seg-faults.
We have to inspect and narrow down this issue.

/cc @vtikha @robotology/wysiwyd-developers

**Comment by vtikha** [comment]
@pattacini, alteady dealing with this, had a debugging session but can't seem to figure out where and how it does it. Will go into it a bit deeper and get it solved.

**Comment by vtikha** [comment]
@Tobias-Fischer The latest commit is positive, please try it whenever you have time and let me know

**Comment by Tobias-Fischer** [comment]
We tested it today, and so far we didn't encounter a crash. Thanks a lot for this fix :)! Closing this issue.
