### ISSUE TITLE
Add SFM viewers to default XML script

### ISSUE THREAD

**Issue by gsaponaro** [robotology/iol#18]
Suggestion: because ```SFM``` and its input connections are already part of the default ```iol.xml.template``` script, it would be useful to add the relative viewers and connections for that module too.

**Comment by pattacini** [comment]
Hi @gsaponaro 

I think users can launch specific `SFM` xml available from stereo-vision repository, if they want to show depth info.

Soon `iol` will be enriched with another viewer and thus I don't want to mess too much the display.

**Comment by gsaponaro** [comment]
I just thought of that because the connections from ```/icub/camcalib/{left,right}/out``` to ```/SFM/{left,right}:i``` are already in the iol XML. Fine then, whatever works better.

**Comment by pattacini** [comment]
Yes, because `SFM` gets launched from the latest `iol` script too.
It's everything in one place, except for the viewer displaying the disparity (which I reckon is not necessary).
