### ISSUE TITLE
iolStateMachineHandler does not compile with OpenCV2

### ISSUE THREAD

**Issue by Tobias-Fischer** [robotology/iol#22]
Hi @pattacini,
Unfortunately the `iolStateMachineHandler` does not compile with OpenCV2:
```
/usr/local/robot/src/iol/src/iolStateMachineHandler/include/module.h:30:10: fatal error: 'opencv2/tracking.hpp' file not found
```
Is it meant to work with OpenCV2 at all or does it only support OpenCV3?

Best,
Tobi

**Comment by pattacini** [comment]
it no longer works with `opencv-2.x.y` due to the tracking mechanism which is always on.
See https://github.com/robotology/iol#dependencies.

**Comment by Tobias-Fischer** [comment]
Ah okay, I missed that it is a hard dependency now. Fixed by installing opencv3 on the machine where it broke.

Thanks :)!
