### ISSUE TITLE
Make iolStateMachineHandler handle multiple objects with the same name

### ISSUE THREAD

**Issue by pattacini** [robotology/iol#27]
Following up #26 we need now to update the way `iolStateMachineHandler` manages objects internally.

As of now, the handling is done through `std::map<std::string,int>`, where the string entry accounts for the object name, thus with two objects of the same categories within the scene `OPC` will end up containing only one instance. We have basically **lost the uniqueness of the object name** and we're required to come up with a fix.

Thank you @giuliavezzani for spotting this out.

cc @vtikha

**Comment by pattacini** [comment]
While trying to better figure it out, I've come to the conclusion that this problem turns to be pretty controversial.

What kind of variable can we use now to identify an object uniquely? In other words, what can replace the string (i.e. name) entry? The recognizer works only with names and, of course, positions can be used as entries in a `std::map`.

**Comment by vtikha** [comment]
I agree, the object name uniqueness cannot be kept. The only uniqueness that comes to mind is as you mention position...
