### ISSUE TITLE
get_matrix service and calibration

### ISSUE THREAD

**Issue by xEnVrE** [robotology/iol#34]
Today, I used the `iolReachingCalibration` `get_matrix` service after a calibration procedure (i.e. using the `calibration_start`/`calibration_stop` services). Right now, the `get_matrix` service returns the calibration matrix only if the optimization problem has been already solved and the actual calibration matrix already evaluated. While I found this behavior reasonable, it also means that, after a new calibration, a module using `iolReachingCalibration` via rpc has to ask for a calibrated 3D point using `get_location` or `get_location_no_look` services to force the evaluation of the matrix. Or the user has to do it manually from the CLI.

Do you think it is a good idea to extend the logic of the `get_matrix` service so that the calibration matrix gets evaluated if it is not already (as done in the `get_location_*` services)?

**Comment by pattacini** [comment]
Yes, I believe yours is a reasonable request 👍 
I'll be implementing this late today.

**Comment by xEnVrE** [comment]
Thank you @pattacini!

**Comment by pattacini** [comment]
Done 👍
