### ISSUE TITLE
Change Lua link in README.md

### ISSUE THREAD

**Issue by alecive** [robotology/iol#7]
It would be better to link the Lua dependency to this page: http://wiki.icub.org/yarpdoc/yarp_swig.html#yarp_swig_lua

**Comment by traversaro** [comment]
cc @alecive It would make sense to link also to the `rFSM` lua library ( https://github.com/kmarkus/rFSM )  that is used to implement the finite state machines.

**Comment by pattacini** [comment]
Right! I'll do that.
thanks!
